## Import The Required Libraries ##

In [2]:
import pandas as pd
import numpy as np

## Load the Files ##

In [3]:
credits = pd.read_csv("tmdb_5000_credits.csv")
movies = pd.read_csv("tmdb_5000_movies.csv")

In [4]:
credits.head()

,movie_id,title,cast,crew
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [5]:
movies.head()

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2015-10-26,880674609,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-07-16,1084939099,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-03-07,284139100,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124

In [6]:
print("Credits:", credits.shape)
print("Movies Dataframe:", movies.shape)

Credits: (4803, 4)
Movies Dataframe: (4803, 20)

## Now the Operations begins.... ##

In [7]:
credits_column_renamed = credits.rename(index = str, columns={"movie_id":"id"})
movies_merge = movies.merge(credits_column_renamed, on = 'id')
print(movies_merge.head())

      budget                                             genres  \
0  237000000  [{"id": 28, "name": "Action"}, {"id": 12, "nam...
1  300000000  [{"id": 12, "name": "Adventure"}, {"id": 14, "...
2  245000000  [{"id": 28, "name": "Action"}, {"id": 12, "nam...
3  250000000  [{"id": 28, "name": "Action"}, {"id": 80, "nam...
4  260000000  [{"id": 28, "name": "Action"}, {"id": 12, "nam...

                                       homepage      id  \
0                   http://www.avatarmovie.com/   19995
1  http://disney.go.com/disneypictures/pirates/     285
2   http://www.sonypictures.com/movies/spectre/  206647
3            http://www.thedarkknightrises.com/   49026
4          http://movies.disney.com/john-carter   49529

                                            keywords original_language  \
0  [{"id": 1463, "name": "culture clash"}, {"id":...                en
1  [{"id": 270, "name": "ocean"}, {"id": 726, "na...                en
2  [{"id": 470, "name": "spy"}, {"id": 818, "name...                en
3  [{"id": 849, "name": "dc comics"}, {"id": 853,...                en
4  [{"id": 818, "name": "based on novel"}, {"id":...                en

                             original_title  \
0                                    Avatar
1  Pirates of the Caribbean: At World's End
2                                   Spectre
3                     The Dark Knight Rises
4                               John Carter

                                            overview  popularity  \
0  In the 22nd century, a paraplegic Marine is di...  150.437577
1  Captain Barbossa, long believed to be dead, ha...  139.082615
2  A cryptic message from Bond’s past sends him o...  107.376788
3  Following the death of District Attorney Harve...  112.312950
4  John Carter is a war-weary, former military ca...   43.926995

                                production_companies  ... runtime  \
0  [{"name": "Ingenious Film Partners", "id": 289...  ...   162.0
1  [{"name": "Walt Disney Pictures", "id": 2}, {"...  ...   169.0
2  [{"name": "Columbia Pictures", "id": 5}, {"nam...  ...   148.0
3  [{"name": "Legendary Pictures", "id": 923}, {"...  ...   165.0
4        [{"name": "Walt Disney Pictures", "id": 2}]  ...   132.0

                                    spoken_languages    status  \
0  [{"iso_639_1": "en", "name": "English"}, {"iso...  Released
1           [{"iso_639_1": "en", "name": "English"}]  Released
2  [{"iso_639_1": "fr", "name": "Fran\u00e7ais"},...  Released
3           [{"iso_639_1": "en", "name": "English"}]  Released
4           [{"iso_639_1": "en", "name": "English"}]  Released

                                          tagline  \
0                     Enter the World of Pandora.
1  At the end of the world, the adventure begins.
2                           A Plan No One Escapes
3                                 The Legend Ends
4            Lost in our world, found in another.

                                    title_x vote_average vote_count  \
0                                    Avatar          7.2      11800
1  Pirates of the Caribbean: At World's End          6.9       4500
2                                   Spectre          6.3       4466
3                     The Dark Knight Rises          7.6       9106
4                               John Carter          6.1       2124

                                    title_y  \
0                                    Avatar
1  Pirates of the Caribbean: At World's End
2                                   Spectre
3                     The Dark Knight Rises
4                               John Carter

                                                cast  \
0  [{"cast_id": 242, "character": "Jake Sully", "...
1  [{"cast_id": 4, "character": "Captain Jack Spa...
2  [{"cast_id": 1, "character": "James Bond", "cr...
3  [{"cast_id": 2, "character": "Bruce Wayne / Ba...
4  [{"cast_id": 5, "character": "John Carter", "c...

                                                crew
0  [{"credit_id": "52fe48009251416c750aca23", "de...
1  [{"credit_id": "52fe4232c3a36847f800b579", "de...
2  [{"credit_id": "54805967c3a36829b5002c41", "de...
3  [{"credit_id": "52fe4781c3a36847f81398c3", "de...
4  [{"credit_id": "52fe479ac3a36847f813eaa3", "de...

[5 rows x 23 columns]

In [8]:
movies_cleaned_df = movies_merge.drop(columns = ['homepage','title_x','title_y','status','production_countries'])
print(movies_cleaned_df.head())
print(movies_cleaned_df.info())
print(movies_cleaned_df.head(1)['overview'])

      budget                                             genres      id  \
0  237000000  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   19995
1  300000000  [{"id": 12, "name": "Adventure"}, {"id": 14, "...     285
2  245000000  [{"id": 28, "name": "Action"}, {"id": 12, "nam...  206647
3  250000000  [{"id": 28, "name": "Action"}, {"id": 80, "nam...   49026
4  260000000  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   49529

                                            keywords original_language  \
0  [{"id": 1463, "name": "culture clash"}, {"id":...                en
1  [{"id": 270, "name": "ocean"}, {"id": 726, "na...                en
2  [{"id": 470, "name": "spy"}, {"id": 818, "name...                en
3  [{"id": 849, "name": "dc comics"}, {"id": 853,...                en
4  [{"id": 818, "name": "based on novel"}, {"id":...                en

                             original_title  \
0                                    Avatar
1  Pirates of the Caribbean: At World's End
2                                   Spectre
3                     The Dark Knight Rises
4                               John Carter

                                            overview  popularity  \
0  In the 22nd century, a paraplegic Marine is di...  150.437577
1  Captain Barbossa, long believed to be dead, ha...  139.082615
2  A cryptic message from Bond’s past sends him o...  107.376788
3  Following the death of District Attorney Harve...  112.312950
4  John Carter is a war-weary, former military ca...   43.926995

                                production_companies release_date     revenue  \
0  [{"name": "Ingenious Film Partners", "id": 289...   2009-12-10  2787965087
1  [{"name": "Walt Disney Pictures", "id": 2}, {"...   2007-05-19   961000000
2  [{"name": "Columbia Pictures", "id": 5}, {"nam...   2015-10-26   880674609
3  [{"name": "Legendary Pictures", "id": 923}, {"...   2012-07-16  1084939099
4        [{"name": "Walt Disney Pictures", "id": 2}]   2012-03-07   284139100

   runtime                                   spoken_languages  \
0    162.0  [{"iso_639_1": "en", "name": "English"}, {"iso...
1    169.0           [{"iso_639_1": "en", "name": "English"}]
2    148.0  [{"iso_639_1": "fr", "name": "Fran\u00e7ais"},...
3    165.0           [{"iso_639_1": "en", "name": "English"}]
4    132.0           [{"iso_639_1": "en", "name": "English"}]

                                          tagline  vote_average  vote_count  \
0                     Enter the World of Pandora.           7.2       11800
1  At the end of the world, the adventure begins.           6.9        4500
2                           A Plan No One Escapes           6.3        4466
3                                 The Legend Ends           7.6        9106
4            Lost in our world, found in another.           6.1        2124

                                                cast  \
0  [{"cast_id": 242, "character": "Jake Sully", "...
1  [{"cast_id": 4, "character": "Captain Jack Spa...
2  [{"cast_id": 1, "character": "James Bond", "cr...
3  [{"cast_id": 2, "character": "Bruce Wayne / Ba...
4  [{"cast_id": 5, "character": "John Carter", "c...

                                                crew
0  [{"credit_id": "52fe48009251416c750aca23", "de...
1  [{"credit_id": "52fe4232c3a36847f800b579", "de...
2  [{"credit_id": "54805967c3a36829b5002c41", "de...
3  [{"credit_id": "52fe4781c3a36847f81398c3", "de...
4  [{"credit_id": "52fe479ac3a36847f813eaa3", "de...
<class 'pandas.DataFrame'>
RangeIndex: 4803 entries, 0 to 4802
Data columns (total 18 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   budget                4803 non-null   int64
 1   genres                4803 non-null   str
 2   id                    4803 non-null   int64
 3   keywords              4803 non-null   str
 4   original_language     4803 non-null   str
 5   original_title        4803 non-null   str
 6   overview              4800 non-null   str
 7   popularity            4803 non-null   float64
 8   production_companies  4803 non-null   str
 9   release_date          4802 non-null   str
 10  revenue               4803 non-null   int64
 11  runtime               4801 non-null   float64
 12  spoken_languages      4803 non-null   str
 13  tagline               3959 non-null   str
 14  vote_average          4803 non-null   float64
 15  vote_count            4803 non-null   int64
 16  cast                  4803 non-null   str
 17  crew                  4803 non-null   str
dtypes: float64(3), int64(4), str(11)
memory usage: 38.4 MB
None
0    In the 22nd century, a paraplegic Marine is di...
Name: overview, dtype: str

In [9]:
movies_cleaned_df['overview'] = movies_cleaned_df['overview'].fillna('')

## Import the TF-IDF library for requirements ##

In [10]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [11]:
tfv = TfidfVectorizer(min_df=3, max_features=None, strip_accents='unicode', analyzer='word',token_pattern=r'\w{1,}', ngram_range=(1, 3), stop_words = 'english')

In [12]:
tfv_matrix = tfv.fit_transform(movies_cleaned_df['overview'])
print(tfv_matrix)
print(tfv_matrix.shape)

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 127220 stored elements and shape (4803, 10417)>
  Coords	Values
  (0, 147)	0.30913114032500133
  (0, 1514)	0.20118856027389753
  (0, 5658)	0.2610479764815685
  (0, 2634)	0.2818968058308857
  (0, 5972)	0.27473323883894724
  (0, 6543)	0.2959108637414297
  (0, 9717)	0.2443539591791674
  (0, 5907)	0.17992707015426693
  (0, 9393)	0.24144219475319856
  (0, 3582)	0.2178825775762986
  (0, 6447)	0.25667782792456906
  (0, 7055)	0.26867652924731417
  (0, 431)	0.21084762228452017
  (0, 1670)	0.27815198887096043
  (0, 148)	0.30913114032500133
  (1, 1408)	0.25331222077109966
  (1, 5397)	0.21777873762971253
  (1, 973)	0.3197826358277298
  (1, 2318)	0.2189240483549797
  (1, 1806)	0.21046232712343155
  (1, 5263)	0.13330162173427934
  (1, 4205)	0.3080300379356447
  (1, 2872)	0.32324825936267076
  (1, 2848)	0.21556897928560056
  (1, 9609)	0.33551759750863897
  :	:
  (4802, 5303)	0.14458839172229582
  (4802, 3238)	0.16238922347130244
  (4802, 6989)	0.12818619387415678
  (4802, 2754)	0.11415766885192152
  (4802, 8137)	0.12006983014875616
  (4802, 1252)	0.1517317799962251
  (4802, 3480)	0.14340155530934393
  (4802, 3736)	0.14859055527694667
  (4802, 677)	0.1348896650905315
  (4802, 2360)	0.15010502652571864
  (4802, 671)	0.15980375315748296
  (4802, 2286)	0.1348896650905315
  (4802, 8046)	0.16238922347130244
  (4802, 4882)	0.14340155530934393
  (4802, 6203)	0.1471738620361153
  (4802, 2176)	0.14227560971626285
  (4802, 2767)	0.3247784469426049
  (4802, 7928)	0.17270633258663715
  (4802, 3965)	0.1553988053389829
  (4802, 123)	0.1553988053389829
  (4802, 873)	0.3552091698129791
  (4802, 2839)	0.17760458490648956
  (4802, 157)	0.16870416903198626
  (4802, 158)	0.17760458490648956
  (4802, 159)	0.17760458490648956
(4803, 10417)

## Requiring a activation function for mimicing the neural networks ##

In [35]:
from sklearn.metrics.pairwise import sigmoid_kernel

In [36]:
sig = sigmoid_kernel(tfv_matrix, tfv_matrix)
print(sig[0])

[0.76163447 0.76159416 0.76159416 ... 0.76159416 0.76159416 0.76159416]

In [31]:
# Reverse mapping of indices and movie titles
indices = pd.Series(movies_cleaned_df.index, index=movies_cleaned_df['original_title']).drop_duplicates()
print(indices)
print(indices['Avatar'])
print(sig[0])
print(list(enumerate(sig[indices['Avatar']])))
print(sorted(list(enumerate(sig[indices['Avatar']])), key=lambda x: x[1], reverse=True))

original_title
Avatar                                         0
Pirates of the Caribbean: At World's End       1
Spectre                                        2
The Dark Knight Rises                          3
John Carter                                    4
                                            ...
El Mariachi                                 4798
Newlyweds                                   4799
Signed, Sealed, Delivered                   4800
Shanghai Calling                            4801
My Date with Drew                           4802
Length: 4803, dtype: int64
0
[0.76163447 0.76159416 0.76159416 ... 0.76159416 0.76159416 0.76159416]

In [38]:
def give_recomendations(title, sig=sig):
    # Getting the index along to the original_title
    idx = indices[title]
    sig_scores = list(enumerate(sig[idx]))
    # Sort the movies
    sig_scores = sorted(sig_scores, key=lambda x: x[1], reverse=True)
    # To Show first 10 recomended movies...
    sig_scores = sig_scores[1:11]
    movie_indices = [i[0] for i in sig_scores]
    # Top 10 most similar movies
    return movies_cleaned_df['original_title'].iloc[movie_indices]

In [33]:
print(give_recomendations("Tears of the Sun"))

807                      The Pacifier
0                              Avatar
790                   American Sniper
1491                         Doomsday
736     Under Siege 2: Dark Territory
2094                           Jaws 2
2130                     The American
1610                            Hanna
3826                 Chain of Command
4361                    Obvious Child
Name: original_title, dtype: str